name: Deploy to Windows Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Windows Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          source: "dist/*"
          target: "C:/inetpub/wwwroot/test"
          strip_components: 1
          overwrite: true

      - name: Setup IIS website
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            if (!(Test-Path "C:\inetpub\wwwroot\test")) { 
              New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\test"
            }
            Import-Module WebAdministration
            if (!(Get-Website -Name "vue-test")) {
              New-Website -Name "vue-test" -Port 80 -PhysicalPath "C:\inetpub\wwwroot\test" -Force
            }
            Start-Website -Name "vue-test"
